# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='ion_sdm.proto',
  package='',
  serialized_pb='\n\rion_sdm.proto\x1a\x10\x64\x65scriptor.proto\"y\n\x15SelfDescribingMessage\x12\x37\n\x0bproto_files\x18\x01 \x02(\x0b\x32\".google.protobuf.FileDescriptorSet\x12\x11\n\ttype_name\x18\x02 \x02(\t\x12\x14\n\x0cmessage_data\x18\x03 \x02(\x0c')




_SELFDESCRIBINGMESSAGE = descriptor.Descriptor(
  name='SelfDescribingMessage',
  full_name='SelfDescribingMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='proto_files', full_name='SelfDescribingMessage.proto_files', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type_name', full_name='SelfDescribingMessage.type_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message_data', full_name='SelfDescribingMessage.message_data', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=35,
  serialized_end=156,
)

import descriptor_pb2

_SELFDESCRIBINGMESSAGE.fields_by_name['proto_files'].message_type = descriptor_pb2._FILEDESCRIPTORSET

class SelfDescribingMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SELFDESCRIBINGMESSAGE
  
  # @@protoc_insertion_point(class_scope:SelfDescribingMessage)

# @@protoc_insertion_point(module_scope)
