# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='ooi_types.proto',
  package='',
  serialized_pb='\n\x0fooi_types.proto\"\x16\n\x05Short\x12\r\n\x05value\x18\x01 \x02(\x11\"\x14\n\x03Int\x12\r\n\x05value\x18\x01 \x02(\x05\"\x15\n\x04Long\x12\r\n\x05value\x18\x01 \x02(\x12\"\x16\n\x05\x46loat\x12\r\n\x05value\x18\x01 \x02(\x02\"\x17\n\x06\x44ouble\x12\r\n\x05value\x18\x01 \x02(\x01\"\x17\n\x06String\x12\r\n\x05value\x18\x01 \x02(\t\"\x18\n\x07\x42oolean\x12\r\n\x05value\x18\x01 \x02(\x08\"\x16\n\x05\x42ytes\x12\r\n\x05value\x18\x01 \x02(\x0c\"u\n\tStructure\x12*\n\x05items\x18\x01 \x03(\x0b\x32\x1b.Structure.StructureElement\x1a<\n\x10StructureElement\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x02(\t\x12\r\n\x05value\x18\x03 \x02(\x0c\")\n\nTypedValue\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x0c\"Z\n\nDataObject\x12#\n\x04\x61tts\x18\x01 \x03(\x0b\x32\x15.DataObject.Attribute\x1a\'\n\tAttribute\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x0c\"~\n\x15\x44\x61taObjectDescription\x12\x0c\n\x04name\x18\x01 \x02(\t\x12.\n\x04\x61tts\x18\x02 \x03(\x0b\x32 .DataObjectDescription.Attribute\x1a\'\n\tAttribute\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x0c\"I\n\x0e\x44\x61taObjectNode\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x02(\x0c\x12\x0c\n\x04type\x18\x03 \x02(\x0c\x12\x0c\n\x04\x66lag\x18\x04 \x02(\x0c\"\x1a\n\tContainer\x12\r\n\x05items\x18\x01 \x03(\x0c\"K\n\x07\x43\x41Store\x12\x1c\n\x05nodes\x18\x01 \x03(\x0b\x32\r.CAStore.Node\x1a\"\n\x04Node\x12\x0b\n\x03key\x18\x01 \x02(\x0c\x12\r\n\x05value\x18\x02 \x02(\x0c')




_SHORT = descriptor.Descriptor(
  name='Short',
  full_name='Short',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='Short.value', index=0,
      number=1, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=19,
  serialized_end=41,
)


_INT = descriptor.Descriptor(
  name='Int',
  full_name='Int',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='Int.value', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=43,
  serialized_end=63,
)


_LONG = descriptor.Descriptor(
  name='Long',
  full_name='Long',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='Long.value', index=0,
      number=1, type=18, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=65,
  serialized_end=86,
)


_FLOAT = descriptor.Descriptor(
  name='Float',
  full_name='Float',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='Float.value', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=88,
  serialized_end=110,
)


_DOUBLE = descriptor.Descriptor(
  name='Double',
  full_name='Double',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='Double.value', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=112,
  serialized_end=135,
)


_STRING = descriptor.Descriptor(
  name='String',
  full_name='String',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='String.value', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=137,
  serialized_end=160,
)


_BOOLEAN = descriptor.Descriptor(
  name='Boolean',
  full_name='Boolean',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='Boolean.value', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=162,
  serialized_end=186,
)


_BYTES = descriptor.Descriptor(
  name='Bytes',
  full_name='Bytes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='Bytes.value', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=188,
  serialized_end=210,
)


_STRUCTURE_STRUCTUREELEMENT = descriptor.Descriptor(
  name='StructureElement',
  full_name='Structure.StructureElement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='Structure.StructureElement.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='Structure.StructureElement.type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='Structure.StructureElement.value', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=269,
  serialized_end=329,
)

_STRUCTURE = descriptor.Descriptor(
  name='Structure',
  full_name='Structure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='items', full_name='Structure.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_STRUCTURE_STRUCTUREELEMENT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=212,
  serialized_end=329,
)


_TYPEDVALUE = descriptor.Descriptor(
  name='TypedValue',
  full_name='TypedValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='TypedValue.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='TypedValue.value', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=331,
  serialized_end=372,
)


_DATAOBJECT_ATTRIBUTE = descriptor.Descriptor(
  name='Attribute',
  full_name='DataObject.Attribute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='DataObject.Attribute.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='DataObject.Attribute.value', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=425,
  serialized_end=464,
)

_DATAOBJECT = descriptor.Descriptor(
  name='DataObject',
  full_name='DataObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='atts', full_name='DataObject.atts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DATAOBJECT_ATTRIBUTE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=374,
  serialized_end=464,
)


_DATAOBJECTDESCRIPTION_ATTRIBUTE = descriptor.Descriptor(
  name='Attribute',
  full_name='DataObjectDescription.Attribute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='DataObjectDescription.Attribute.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='DataObjectDescription.Attribute.value', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=425,
  serialized_end=464,
)

_DATAOBJECTDESCRIPTION = descriptor.Descriptor(
  name='DataObjectDescription',
  full_name='DataObjectDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='DataObjectDescription.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='atts', full_name='DataObjectDescription.atts', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DATAOBJECTDESCRIPTION_ATTRIBUTE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=466,
  serialized_end=592,
)


_DATAOBJECTNODE = descriptor.Descriptor(
  name='DataObjectNode',
  full_name='DataObjectNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='DataObjectNode.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='content', full_name='DataObjectNode.content', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='DataObjectNode.type', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flag', full_name='DataObjectNode.flag', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=594,
  serialized_end=667,
)


_CONTAINER = descriptor.Descriptor(
  name='Container',
  full_name='Container',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='items', full_name='Container.items', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=669,
  serialized_end=695,
)


_CASTORE_NODE = descriptor.Descriptor(
  name='Node',
  full_name='CAStore.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='CAStore.Node.key', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='CAStore.Node.value', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=738,
  serialized_end=772,
)

_CASTORE = descriptor.Descriptor(
  name='CAStore',
  full_name='CAStore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='nodes', full_name='CAStore.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CASTORE_NODE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=697,
  serialized_end=772,
)


_STRUCTURE_STRUCTUREELEMENT.containing_type = _STRUCTURE;
_STRUCTURE.fields_by_name['items'].message_type = _STRUCTURE_STRUCTUREELEMENT
_DATAOBJECT_ATTRIBUTE.containing_type = _DATAOBJECT;
_DATAOBJECT.fields_by_name['atts'].message_type = _DATAOBJECT_ATTRIBUTE
_DATAOBJECTDESCRIPTION_ATTRIBUTE.containing_type = _DATAOBJECTDESCRIPTION;
_DATAOBJECTDESCRIPTION.fields_by_name['atts'].message_type = _DATAOBJECTDESCRIPTION_ATTRIBUTE
_CASTORE_NODE.containing_type = _CASTORE;
_CASTORE.fields_by_name['nodes'].message_type = _CASTORE_NODE

class Short(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SHORT
  
  # @@protoc_insertion_point(class_scope:Short)

class Int(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INT
  
  # @@protoc_insertion_point(class_scope:Int)

class Long(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LONG
  
  # @@protoc_insertion_point(class_scope:Long)

class Float(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FLOAT
  
  # @@protoc_insertion_point(class_scope:Float)

class Double(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DOUBLE
  
  # @@protoc_insertion_point(class_scope:Double)

class String(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STRING
  
  # @@protoc_insertion_point(class_scope:String)

class Boolean(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BOOLEAN
  
  # @@protoc_insertion_point(class_scope:Boolean)

class Bytes(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BYTES
  
  # @@protoc_insertion_point(class_scope:Bytes)

class Structure(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class StructureElement(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _STRUCTURE_STRUCTUREELEMENT
    
    # @@protoc_insertion_point(class_scope:Structure.StructureElement)
  DESCRIPTOR = _STRUCTURE
  
  # @@protoc_insertion_point(class_scope:Structure)

class TypedValue(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TYPEDVALUE
  
  # @@protoc_insertion_point(class_scope:TypedValue)

class DataObject(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Attribute(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _DATAOBJECT_ATTRIBUTE
    
    # @@protoc_insertion_point(class_scope:DataObject.Attribute)
  DESCRIPTOR = _DATAOBJECT
  
  # @@protoc_insertion_point(class_scope:DataObject)

class DataObjectDescription(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Attribute(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _DATAOBJECTDESCRIPTION_ATTRIBUTE
    
    # @@protoc_insertion_point(class_scope:DataObjectDescription.Attribute)
  DESCRIPTOR = _DATAOBJECTDESCRIPTION
  
  # @@protoc_insertion_point(class_scope:DataObjectDescription)

class DataObjectNode(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DATAOBJECTNODE
  
  # @@protoc_insertion_point(class_scope:DataObjectNode)

class Container(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTAINER
  
  # @@protoc_insertion_point(class_scope:Container)

class CAStore(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Node(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CASTORE_NODE
    
    # @@protoc_insertion_point(class_scope:CAStore.Node)
  DESCRIPTOR = _CASTORE
  
  # @@protoc_insertion_point(class_scope:CAStore)

# @@protoc_insertion_point(module_scope)
